In [74]:
import pandas as pd
import numpy as np
#https://www.kaggle.com/ashirwadsangwan/imdb-dataset

In [75]:
#definindo os caminhos dos arquivos
names = pd.read_csv('C:/Users/fic/Documents/IMDb Dataset/name.basics.tsv/name.basics.tsv', sep = "\t")


In [76]:
titles = pd.read_csv('C:/Users/fic/Documents/IMDb Dataset/title.akas.tsv/title.akas.tsv', sep = "\t")


In [77]:
titles_basic = pd.read_csv('C:/Users/fic/Documents/IMDb Dataset/title.basics.tsv/title.basics.tsv', sep = "\t")


In [78]:
titles_principal = pd.read_csv('C:/Users/fic/Documents/IMDb Datasettitle.principals.tsv/title.principals.tsv', sep = "\t")


FileNotFoundError: [Errno 2] File b'C:/Users/fic/Documents/IMDb Datasettitle.principals.tsv/title.principals.tsv' does not exist: b'C:/Users/fic/Documents/IMDb Datasettitle.principals.tsv/title.principals.tsv'

In [79]:
titles_rating = pd.read_csv('C:/Users/fic/Documents/IMDb Dataset/title.ratings.tsv/title.ratings.tsv', sep = "\t")

In [80]:
names = names.replace('\\N', np.nan)

In [81]:
titles = titles.replace('\\N', np.nan)

In [82]:
titles_basic = titles_basic.replace('\\N', np.nan)

In [83]:
titles_principal = titles_principal.replace('\\N', np.nan)

In [84]:
titles_rating = titles_rating.replace('\\N', np.nan)

In [115]:
names.head()

nconst      primaryName birthYear deathYear  \
0  nm0000001     Fred Astaire      1899      1987   
1  nm0000002    Lauren Bacall      1924      2014   
2  nm0000003  Brigitte Bardot      1934       NaN   
3  nm0000004     John Belushi      1949      1982   
4  nm0000005   Ingmar Bergman      1918      2007   

                primaryProfession                           knownForTitles  
0  soundtrack,actor,miscellaneous  tt0050419,tt0053137,tt0072308,tt0043044  
1              actress,soundtrack  tt0071877,tt0117057,tt0038355,tt0037382  
2     actress,soundtrack,producer  tt0054452,tt0049189,tt0059956,tt0057345  
3         actor,writer,soundtrack  tt0077975,tt0072562,tt0080455,tt0078723  
4           writer,director,actor  tt0069467,tt0050976,tt0083922,tt0050986

In [123]:
names.count()

nconst               9706922
primaryName          9706922
birthYear             491281
deathYear             172005
primaryProfession    7775897
knownForTitles       8017326
dtype: int64

In [124]:
names['primaryName'].unique()

array(['Fred Astaire', 'Lauren Bacall', 'Brigitte Bardot', ...,
       'Essias Loberg', 'Harikrishnan Rajan', 'Aayush Nair'], dtype=object)

In [125]:
names['Ano Falecimento'].unique()

array(['soundtrack,actor,miscellaneous', 'actress,soundtrack',
       'actress,soundtrack,producer', ...,
       'casting_department,art_department,costume_designer',
       'publicist,production_designer',
       'producer,casting_department,assistant'], dtype=object)

In [134]:
names['knownForTitles'].unique()

array(['tt0050419,tt0053137,tt0072308,tt0043044',
       'tt0071877,tt0117057,tt0038355,tt0037382',
       'tt0054452,tt0049189,tt0059956,tt0057345', ...,
       'tt8744286,tt9046122', 'tt8744286', 'tt8325250'], dtype=object)

In [140]:
names.columns = ['nconst','primeiro_nome','ano_nascimento','ano_falecimento','profissao_primaria','knownForTitles']


In [141]:
names.head()

nconst    primeiro_nome ano_nascimento ano_falecimento  \
0  nm0000001     Fred Astaire           1899            1987   
1  nm0000002    Lauren Bacall           1924            2014   
2  nm0000003  Brigitte Bardot           1934             NaN   
3  nm0000004     John Belushi           1949            1982   
4  nm0000005   Ingmar Bergman           1918            2007   

               profissao_primaria                           knownForTitles  
0  soundtrack,actor,miscellaneous  tt0050419,tt0053137,tt0072308,tt0043044  
1              actress,soundtrack  tt0071877,tt0117057,tt0038355,tt0037382  
2     actress,soundtrack,producer  tt0054452,tt0049189,tt0059956,tt0057345  
3         actor,writer,soundtrack  tt0077975,tt0072562,tt0080455,tt0078723  
4           writer,director,actor  tt0069467,tt0050976,tt0083922,tt0050986

In [86]:
titles.head()

titleId  ordering                      title region language  \
0  tt0000001         1  Carmencita - spanyol tánc     HU      NaN   
1  tt0000001         2                 Καρμενσίτα     GR      NaN   
2  tt0000001         3                 Карменсита     RU      NaN   
3  tt0000001         4                 Carmencita     US      NaN   
4  tt0000001         5                 Carmencita    NaN      NaN   

         types attributes isOriginalTitle  
0  imdbDisplay        NaN               0  
1          NaN        NaN               0  
2          NaN        NaN               0  
3          NaN        NaN               0  
4     original        NaN               1

In [127]:
titles.count()

titleId            19322610
ordering           19322610
title              19322610
region             18861073
language           16126439
types               1093713
attributes           180679
isOriginalTitle    19320480
dtype: int64

In [128]:
titles['title'].unique()

array(['Carmencita - spanyol tánc', 'Καρμενσίτα', 'Карменсита', ...,
       'Rahibe 2', 'The Possessed Nun', 'The Demonic Nun'], dtype=object)

In [129]:
titles['region'].unique()

array(['HU', 'GR', 'RU', 'US', nan, 'FR', 'RO', 'GB', 'PT', 'ES', 'UY',
       'DE', 'IT', 'FI', 'RS', 'PL', 'AR', 'BR', 'XWW', 'TR', 'DK', 'XEU',
       'SK', 'CZ', 'SE', 'MX', 'XYU', 'AT', 'VE', 'CSHH', 'SI', 'JP',
       'AU', 'NL', 'NO', 'IR', 'UA', 'CA', 'CO', 'BG', 'BE', 'IN', 'DZ',
       'CH', 'NZ', 'BF', 'XWG', 'VN', 'SUHH', 'EE', 'IS', 'DDDE', 'HR',
       'XKO', 'CL', 'LT', 'EG', 'HK', 'BY', 'GE', 'BA', 'PE', 'PA', 'CN',
       'XSI', 'YUCS', 'IE', 'XSA', 'IL', 'CU', 'AL', 'BO', 'ZA', 'KR',
       'MY', 'SG', 'BUMM', 'XPI', 'BJ', 'PR', 'CM', 'AZ', 'TH', 'DO',
       'EC', 'LV', 'MA', 'GL', 'LI', 'LU', 'PH', 'ID', 'PY', 'MZ', 'BM',
       'TW', 'JM', 'MD', 'LB', 'IQ', 'TM', 'MK', 'CR', 'TN', 'NG', 'HT',
       'SN', 'GH', 'CI', 'JO', 'KG', 'PK', 'LK', 'GT', 'TJ', 'NE', 'GN',
       'VDVN', 'TD', 'SO', 'SD', 'MC', 'CG', 'TT', 'GA', 'BS', 'LY', 'SY',
       'AO', 'KH', 'SV', 'MR', 'AF', 'MG', 'ML', 'GY', 'CY', 'ET', 'XAS',
       'UZ', 'SR', 'MT', 'AM', 'TG', 'PG', 'MU', 'BI', 

In [130]:
titles['language'].unique()

array([nan, 'sv', 'en', 'tr', 'es', 'sr', 'cs', 'fa', 'fr', 'bg', 'ca',
       'nl', 'qbn', 'pt', 'ru', 'qbp', 'ar', 'cmn', 'rn', 'bs', 'de',
       'hi', 'yi', 'qbo', 'uk', 'ka', 'hr', 'sl', 'he', 'tg', 'sk', 'kk',
       'el', 'fi', 'it', 'da', 'gsw', 'az', 'ms', 'pl', 'mr', 'uz', 'gl',
       'th', 'ta', 'eu', 'yue', 'af', 'la', 'hy', 'ur', 'bn', 'te', 'be',
       'lt', 'mk', 'et', 'gd', 'tl', 'lv', 'cy', 'id', 'qal', 'goh', 'ml',
       'ro', 'ja', 'hu', 'pa', 'no', 'is', 'sq', 'vi', 'ga', 'gu', 'ps',
       'nqo', 'sd', 'kn', 'xh', 'mi', 'wo', 'zu', 'rm', 'prs', 'ky',
       'fro', 'mn', 'lo', 'my', 'zh', 'am', 'qac', 'ku', 'ne', 'ko',
       'haw', 'myv', 'iu', 'st', 'tn', 'cr'], dtype=object)

In [131]:
titles['types'].unique()

array(['imdbDisplay', nan, 'original', 'alternative', 'dvd', 'festival',
       'working', 'tv', 'video', 'tv\x02working', 'tv\x02video',
       'video\x02working', 'festival\x02working', 'dvd\x02video',
       'dvd\x02imdbDisplay', 'dvd\x02working'], dtype=object)

In [132]:
titles['attributes'].unique()

array([nan, 'literal English title', 'informal alternative title',
       'promotional title', 'complete title', 'poster title',
       'literal translation of working title', 'premiere title',
       'informal title', 'short title', 'première title',
       'bowdlerized title', 'reissue title', 'informal English title',
       'alternative spelling', 'original script title',
       'informal literal title', 'copyright title', 'long title',
       'literal title', 'transliterated ISO-LATIN-1 title',
       'informal short title', 'review title', 'new title', 'subtitle',
       'original subtitled version', 'cut version',
       'video catalogue title', 'second part title',
       'fourth season title', 'third part title', 'fifth season title',
       'series title', 'recut version', 'pre-release title',
       'theatrical title', 'first part title',
       'informal literal English title', '8mm release title',
       'Los Angeles première title', 'DVD box title',
       'second copyrig

In [133]:
titles['isOriginalTitle'].unique()

array([0, 1, '0', '1', nan], dtype=object)

In [87]:
titles_basic.head()

tconst titleType            primaryTitle           originalTitle  \
0  tt0000001     short              Carmencita              Carmencita   
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens   
2  tt0000003     short          Pauvre Pierrot          Pauvre Pierrot   
3  tt0000004     short             Un bon bock             Un bon bock   
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene   

   isAdult startYear endYear runtimeMinutes                    genres  
0        0      1894     NaN              1         Documentary,Short  
1        0      1892     NaN              5           Animation,Short  
2        0      1892     NaN              4  Animation,Comedy,Romance  
3        0      1892     NaN            NaN           Animation,Short  
4        0      1893     NaN              1              Comedy,Short

In [117]:
titles_basic.count()

tconst            6321302
titleType         6321302
primaryTitle      6321292
originalTitle     6321117
isAdult           6321302
startYear         5951344
endYear             54362
runtimeMinutes    1865942
genres            5819979
dtype: int64

In [95]:
titles_basic['titleType'].unique()

array(['short', 'movie', 'tvMovie', 'tvSeries', 'tvEpisode', 'tvShort',
       'tvMiniSeries', 'tvSpecial', 'video', 'videoGame'], dtype=object)

In [96]:
titles_basic['primaryTitle'].unique()

array(['Carmencita', 'Le clown et ses chiens', 'Pauvre Pierrot', ...,
       'Danira Boukhriss Terkessidis', "Horrid Henry's Comic Caper",
       'Horrid Henry Knows It All'], dtype=object)

In [97]:
titles_basic['originalTitle'].unique()

array(['Carmencita', 'Le clown et ses chiens', 'Pauvre Pierrot', ...,
       'Danira Boukhriss Terkessidis', "Horrid Henry's Comic Caper",
       'Horrid Henry Knows It All'], dtype=object)

In [98]:
titles_basic['isAdult'].unique()

array([   0,    1, 2019, 2004, 2014, 2018, 2015, 1994, 2005], dtype=int64)

In [99]:
titles_basic['startYear'].unique()

array([1894, 1892, 1893, 1895, 1896, 1898, 1897, 1900, 1899, 1901, 1904,
       1903, 1902, 1905, 1912, 1907, 1906, 1908, 1910, 1909, 1914, 1911,
       1913, 1915, 1919, 1916, 1917, 1918, 1936, 1925, 1920, 1922, 1921,
       1923, 1924, 1928, 1926, 1927, 1929, 1993, 1935, 1930, 1942, 1933,
       1934, 1931, 1932, 1939, 1937, 1950, 1938, 1951, 1945, 1983, 1946,
       1940, 1944, 1949, 1947, 1958, 1941, 1952, 1970, 1957, 1943, 1948,
       1959, 2001, 1953, 1954, 1965, 1973, 1961, 1995, 1955, 1962, 1956,
       1960, 1964, 1967, 1968, 1963, 1969, 1985, 1971, 1972, 1966, 1992,
       1976, 1990, 1986, 1979, 1974, 1981, 1988, 1975, 1978, 1977, 1989,
       '1971', '1972', '1970', '1967', '1973', '1974', '1976', '1969',
       '1968', '1985', nan, '1981', '1977', '1980', '1986', '1965',
       '1975', '1978', '2010', '2018', '1979', '1989', '1988', '1984',
       '1966', '1983', '1995', '1982', '1992', '1991', '1952', '1987',
       '1963', '1961', '1994', '1993', '1990', '1964', '1957',

In [100]:
titles_basic['endYear'].unique()

array([nan, '1947', '1950', '1949', '1958', '1951', '1952', '1954',
       '1957', '1953', '1956', '1967', '1971', '1959', '1955', '1963',
       '1960', '1961', '1965', '1980', '2016', '1986', '1962', '1972',
       '1966', '1970', '2009', '1973', '1987', '1991', '1974', '1992',
       '1976', '1975', '1982', '2010', '1984', '1964', '1968', '1989',
       '1969', '1994', '2004', '1981', '1977', '1999', '1988', '2003',
       '1978', '2001', '2013', '1993', '1997', '1996', '2011', '2005',
       '1995', '1979', '2006', '1985', '1983', '1998', '1990', '2008',
       '2007', '2015', '2014', '2000', '2019', '2002', '2018', '2012',
       '2020', '1948', '2017', '1938', '1942', '1933', '2021', '2026',
       '2022', '1946', '1945', '1941', '1937', '1939', '1932', '2025',
       '1936', '1924', '1927', '1935', '2024', '2027', '24'], dtype=object)

In [101]:
titles_basic['runtimeMinutes'].unique()

array(['1', '5', '4', nan, '45', '2', '0', '3', '20', '13', '6', '11',
       '9', '10', '8', '15', '21', '16', '12', '14', '7', '24', '100',
       '17', '70', '25', '120', '36', '18', '30', '19', '38', '58', '50',
       '34', '28', '44', '23', '51', '40', '92', '60', '56', '53', '26',
       '41', '48', '68', '33', '31', '29', '43', '46', '27', '32', '76',
       '85', '55', '121', '89', '37', '69', '22', '54', '90', '35', '150',
       '64', '96', '49', '61', '101', '300', '57', '99', '110', '39',
       '88', '52', '86', '72', '78', '75', '450', '148', '59', '63',
       '112', '1428', '84', '65', '42', '74', '105', '73', '82', '81',
       '199', '109', '219', '80', '67', '310', '195', '440', '77', '293',
       '97', '62', '71', '47', '250', '421', '360', '180', '66', '163',
       '93', '400', '95', '83', '116', '320', '125', '127', '138', '460',
       '350', '374', '480', '87', '130', '108', '79', '136', '94', '600',
       '240', '117', '146', '104', '418', '330', '242', '22

In [102]:
titles_basic['genres'].unique()

array(['Documentary,Short', 'Animation,Short', 'Animation,Comedy,Romance',
       ..., 'Musical,Reality-TV,Talk-Show', 'Animation,Short,Talk-Show',
       'Comedy,Mystery,Talk-Show'], dtype=object)

In [ ]:
#pausa no processo

In [88]:
titles_principal.head()

titleId  ordering                      title region language  \
0  tt0000001         1  Carmencita - spanyol tánc     HU      NaN   
1  tt0000001         2                 Καρμενσίτα     GR      NaN   
2  tt0000001         3                 Карменсита     RU      NaN   
3  tt0000001         4                 Carmencita     US      NaN   
4  tt0000001         5                 Carmencita    NaN      NaN   

         types attributes isOriginalTitle  
0  imdbDisplay        NaN               0  
1          NaN        NaN               0  
2          NaN        NaN               0  
3          NaN        NaN               0  
4     original        NaN               1

In [118]:
titles_principal.count()

titleId            19322610
ordering           19322610
title              19322610
region             18861073
language           16126439
types               1093713
attributes           180679
isOriginalTitle    19320480
dtype: int64

In [103]:
titles_principal['ordering'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99], dtype=int64)

In [106]:
titles_principal['title'].unique()

array(['Carmencita - spanyol tánc', 'Καρμενσίτα', 'Карменсита', ...,
       'Rahibe 2', 'The Possessed Nun', 'The Demonic Nun'], dtype=object)

In [107]:
titles_principal['region'].unique()

array(['HU', 'GR', 'RU', 'US', nan, 'FR', 'RO', 'GB', 'PT', 'ES', 'UY',
       'DE', 'IT', 'FI', 'RS', 'PL', 'AR', 'BR', 'XWW', 'TR', 'DK', 'XEU',
       'SK', 'CZ', 'SE', 'MX', 'XYU', 'AT', 'VE', 'CSHH', 'SI', 'JP',
       'AU', 'NL', 'NO', 'IR', 'UA', 'CA', 'CO', 'BG', 'BE', 'IN', 'DZ',
       'CH', 'NZ', 'BF', 'XWG', 'VN', 'SUHH', 'EE', 'IS', 'DDDE', 'HR',
       'XKO', 'CL', 'LT', 'EG', 'HK', 'BY', 'GE', 'BA', 'PE', 'PA', 'CN',
       'XSI', 'YUCS', 'IE', 'XSA', 'IL', 'CU', 'AL', 'BO', 'ZA', 'KR',
       'MY', 'SG', 'BUMM', 'XPI', 'BJ', 'PR', 'CM', 'AZ', 'TH', 'DO',
       'EC', 'LV', 'MA', 'GL', 'LI', 'LU', 'PH', 'ID', 'PY', 'MZ', 'BM',
       'TW', 'JM', 'MD', 'LB', 'IQ', 'TM', 'MK', 'CR', 'TN', 'NG', 'HT',
       'SN', 'GH', 'CI', 'JO', 'KG', 'PK', 'LK', 'GT', 'TJ', 'NE', 'GN',
       'VDVN', 'TD', 'SO', 'SD', 'MC', 'CG', 'TT', 'GA', 'BS', 'LY', 'SY',
       'AO', 'KH', 'SV', 'MR', 'AF', 'MG', 'ML', 'GY', 'CY', 'ET', 'XAS',
       'UZ', 'SR', 'MT', 'AM', 'TG', 'PG', 'MU', 'BI', 

In [108]:
titles_principal['language'].unique()

array([nan, 'sv', 'en', 'tr', 'es', 'sr', 'cs', 'fa', 'fr', 'bg', 'ca',
       'nl', 'qbn', 'pt', 'ru', 'qbp', 'ar', 'cmn', 'rn', 'bs', 'de',
       'hi', 'yi', 'qbo', 'uk', 'ka', 'hr', 'sl', 'he', 'tg', 'sk', 'kk',
       'el', 'fi', 'it', 'da', 'gsw', 'az', 'ms', 'pl', 'mr', 'uz', 'gl',
       'th', 'ta', 'eu', 'yue', 'af', 'la', 'hy', 'ur', 'bn', 'te', 'be',
       'lt', 'mk', 'et', 'gd', 'tl', 'lv', 'cy', 'id', 'qal', 'goh', 'ml',
       'ro', 'ja', 'hu', 'pa', 'no', 'is', 'sq', 'vi', 'ga', 'gu', 'ps',
       'nqo', 'sd', 'kn', 'xh', 'mi', 'wo', 'zu', 'rm', 'prs', 'ky',
       'fro', 'mn', 'lo', 'my', 'zh', 'am', 'qac', 'ku', 'ne', 'ko',
       'haw', 'myv', 'iu', 'st', 'tn', 'cr'], dtype=object)

In [109]:
titles_principal['types'].unique()

array(['imdbDisplay', nan, 'original', 'alternative', 'dvd', 'festival',
       'working', 'tv', 'video', 'tv\x02working', 'tv\x02video',
       'video\x02working', 'festival\x02working', 'dvd\x02video',
       'dvd\x02imdbDisplay', 'dvd\x02working'], dtype=object)

In [110]:
titles_principal['attributes'].unique()

array([nan, 'literal English title', 'informal alternative title',
       'promotional title', 'complete title', 'poster title',
       'literal translation of working title', 'premiere title',
       'informal title', 'short title', 'première title',
       'bowdlerized title', 'reissue title', 'informal English title',
       'alternative spelling', 'original script title',
       'informal literal title', 'copyright title', 'long title',
       'literal title', 'transliterated ISO-LATIN-1 title',
       'informal short title', 'review title', 'new title', 'subtitle',
       'original subtitled version', 'cut version',
       'video catalogue title', 'second part title',
       'fourth season title', 'third part title', 'fifth season title',
       'series title', 'recut version', 'pre-release title',
       'theatrical title', 'first part title',
       'informal literal English title', '8mm release title',
       'Los Angeles première title', 'DVD box title',
       'second copyrig

In [112]:
titles_principal['isOriginalTitle'].unique()

array([0, 1, '0', '1', nan], dtype=object)

In [113]:
titles_rating.head()

tconst  averageRating  numVotes
0  tt0000001            5.6      1550
1  tt0000002            6.1       186
2  tt0000003            6.5      1207
3  tt0000004            6.2       113
4  tt0000005            6.1      1934

In [119]:
titles_rating.count()

tconst           993153
averageRating    993153
numVotes         993153
dtype: int64

In [ ]:
#titles_principal com os nomes dos atores names